---
- name: Add host name in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^127\.0\.0\.1(?!{{'\t'}}{{hostname_name}})(.*)"
    line="127.0.0.1{{'\t'}}{{ hostname_name }}\1"
    state=present
    backrefs=yes
  tags: [hostname]
