---

- include: config-hostname.yml tags=config

- name: Clean existing
  shell: rm -f {{mci_home}}/mci-api/build/distributions/mci-0.1-1.noarch.rpm
  sudo: true

- name: Start cassandra
  service: name=cassandra state=started
  sudo: true

- name: Checkout MCI code
  git: repo=https://github.com/SharedHealth/MCI-Resigtry.git
    dest={{mci_home}}
    update=yes

- name: Make gradlew executable
  command: chdir={{mci_home}} chmod 755 gradlew

- name: Build rpm distribution
  shell: chdir={{mci_home}} ./gradlew clean dist
  sudo: true
  async: 45
  poll: 5

- name: Check for existing installations
  shell: rpm -q mci-0.1-1
  register: mci_installed
  ignore_errors: yes
  sudo: true

- name: Remove existing installation if any
  shell: yum remove -y mci-0.1-1
  when: mci_installed.rc == 0
  sudo: true

- name: Install mci
  shell: yum install -y {{mci_home}}/mci-api/build/distributions/mci-0.1-1.noarch.rpm
  sudo: true

- name: Start mci
  service: name=mci state=started
  sudo: true

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Allow mci port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "MCI"
  sudo: true
  when: iptablesrules.stdout.find("MCI") == -1

- name: save iptables
  command: service iptables save
  sudo: true
